const API_WS = "ws://localhost:8000" + "/ws"
const API_CHART = "ws://localhost:8000" + "/ws"
const API_REGISTER = "//localhost:8000" + "/api/register"
const API_LOGIN = "//localhost:8000" + "/api/login"
const API_CHAT = "//localhost:8000" + "/api/chat"